data:
  data_path: "./data/RAFT.pdf"

store:
  docstore_path: "./store/docstore/docstore.pkl"
  graph_state_path: './store/graph_state/example.pkl'
  vectorstore_directory: "./store/vectorstore/multi_modal_data"
  graph_png_path: "graph_output.png"
